apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - bot-secrets.sops.yaml
  - deployment.yaml
# Add core infrastructure resources here (e.g., namespaces, CRDs, etc.)
